version: '3.8'

services:
  postgres:
    container_name: LocalPostgres
    image: postgres:16.0-alpine
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      # Custom init SQL script to create the database schema if it isn't setup yet
      - ./templates/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
