version: '3.8'

services:
  redis:
    container_name: LocalRedis
    image: redis:7.2.1-alpine
    network_mode: host
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
  postgres:
    container_name: LocalPostgres
    image: postgres:16.0-alpine
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      # Custom init SQL script to add example data (and example schema without an ORM)
      - ./templates/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
